---
- name: Configuration en SSH de plusieurs machines pour un CMS hautement disponible
  become: true
  vars:
    chemin_fichier_adresses_ipv4: "./adresse_ipv4.log"
  
  tasks:
  - name: DONNE LES DROITS D'EXECUTION POUR LE SCRIPT DE CONFIGURATION DE LA MACHINE
    ansible.builtin.command: chmod o+x /root/.deploy/scan_ip.sh
    become: true

  - name: Execute transformer_en_routeur.sh script
    ansible.builtin.command: bash /root/.deploy/scan_ip.sh
    
  - name: DONNE LES DROITS D'EXECUTION POUR LE SCRIPT DE CONFIGURATION DE LA MACHINE
    ansible.builtin.command: chmod o+x /root/.deploy/ssh_auto.sh
    become: true

  - name: Execute transformer_en_routeur.sh script
    ansible.builtin.command: bash /root/.deploy/ssh_auto.sh
    
  - name: COMMON | Installation de tous les élèments commun aux hôtes
    hosts: all
    roles:
      - common
 
  - name: COPIE DES FICHIERS DE CONFIGURATIONS SSH DE LA MACHINE
    ansible.builtin.copy:
      src: /root/.deploy/transformer_en_routeur.sh
      dest: /home/{{ ansible_facts.hostname }}/transformer_en_routeur.sh
      remote_src: yes
    roles:
      - machine1
      
  - name: DONNE LES DROITS D'EXECUTION POUR LE SCRIPT DE CONFIGURATION DE LA MACHINE
    ansible.builtin.command: chmod o+x /home/{{ ansible_facts.hostname }}/transformer_en_routeur.sh
    become: true
    roles:
      - machine1

  - name: Execute transformer_en_routeur.sh script
    ansible.builtin.command: bash /home/{{ ansible_facts.hostname }}/transformer_en_routeur.sh
    roles:
      - machine1

  
  - name:  Installation à distance des diffèrents systèmes
    hosts: "{{ hosts }}"
    roles:
      - "{{ name }}"
    with_items:
    - { name: "machine0", hosts: "machine0" }
    - { name: "machine1", hosts: "machine1" }
    - { name: "machine2", hosts: "machine2" }
    - { name: "machine3", hosts: "machine3" }
    - { name: "machine4", hosts: "machine4" }
    - { name: "machine5", hosts: "machine5" }
    - { name: "machine6", hosts: "machine6" }

