---
- name: Configuration en SSH de plusieurs machines pour un CMS hautement disponible
  hosts: connexion_local
  connection: local
  become: true
  vars:
    chemin_fichier_adresses_ipv4: "./adresse_ipv4.log"
  
  tasks:
    
  - name: DONNE LES DROITS D'EXECUTION POUR LE SCRIPT DE CONFIGURATION DE CONFIGURATION SSH POUR LA SESSION ANSIBLE
    ansible.builtin.command: chmod o+x /root/.deploy/ssh_auto.sh
    become: true

  - name: EXECUTE LE SCRIPT DE CONFIGURATION DE CONFIGURATION SSH POUR LA SESSION ANSIBLE
    ansible.builtin.command: bash /root/.deploy/ssh_auto.sh
    
- name: COMMON | Installation de tous les élèments commun aux hôtes
  hosts: machine_sans_configuration
  roles:
    - common

- name: routeurs | Installation de tous les élèments commun aux hôtes
  hosts: relai
  roles:
    - relai
    
- name: COMMON | Installation de tous les élèments commun aux hôtes
  hosts: relai
  roles:
    - relai

