
---
- name: Installer les config necessaire pour rendre fonctionelle la navigation à travers le réseau
  hosts: webservers
  become: true
  
  vars:
    http_proxy: "http://proxy.infra.dgfip:3128/"
    repo_font: "https://github.com/adelfortin/fontspowerline"
    repo_export: "https://github.com/adelfortin/exportation"
  
  tasks:
  # Configuration et installation de DNF et EPEL
  - name: CONFIG DNF | Ajout du proxy dans le fichier de configuration de dnf
    lineinfile:
      path: /etc/dnf/dnf.conf
      line: "proxy={{ http_proxy }}"
    
  # Installation de git sur les machines
  - name: INSTALL git
    dnf:
      name: git

  - name: Configuration du proxy gir
    command: "git config --global http.proxy {{ http_proxy }}"

  - name: Récupére l'utilisateur courant
    command: whoami
    register: username
    become_user: "{{ ansible_facts.hostname }}"

  - name: vérifie que la valeur est bien enregistré
    debug:
      var: username.stdout

  - name: Copier les polices de caractère sur la machine
    git:
      repo: "{{ repo_font }}"
      dest: "/home/{{ username.stdout }}/.fonts/"
      clone: yes
      update: yes

  - name: Installe les polices de caractères sur la machine
      command: "bash /home/{{ username.stdout }}/.fonts/install.sh"

  - name: Installe les prompt personnalisé 
    git:
      repo: "{{ repo_export }}"
      dest: "/home/{{ username.stdout }}/.bash/themes/agnoster-bash/"
      clone: yes
      update: yes

  - name: CREATION DES DOSSIERS POUR ROOT
    file:
      path: /root/.bash/themes/agnoster-bash
      state: directory

  - name: Déplace le fichier de configuation BASHRC au bon endroit
    command: "mv /home/{{ username.stdout }}/.bash/themes/agnoster-bash/.bashrc /home/{{ username.stdout }}/.bashrc"

  - name: Installation du theme du prompt de root
    command: "cp -f /home/{{ username.stdout }}/.bash/themes/agnoster-bash/agnoster.bash /root/.bash/themes/agnoster-bash/"
    
  - name: Préparation du .bashrc de root
    command: "cp /home/{{ username.stdout }}/.bashrc /root/"
