
---
- name: Installer les config necessaire pour rendre fonctionelle la navigation à travers le réseau
  hosts: connexion_local
  connection: local
  become: true
  vars:
    ancienne_adresse: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    adresse_ipv4_numero_zero: "192.168.83.1"
    interface_zero: "enp0s8"
    adresse_de_passerelle_une: 192.168.83.2
    adresse_dns_une: 10.156.32.33
    adresse_dns_deux: 10.154.59.104
    hostname_machine_une: "supervision"
  tasks:
  
    # configure le hostname de cette machine
    - name: configuration du hostname
      ansible.builtin.command: hostnamectl set-hostname {{ hostname_machine_une }}
      become: true
      tags: machine0
      
    - name: Configure la première interface
      ansible.builtin.command: nmcli connection add type ethernet con-name INTERNET ifname {{ interface_zero }} ipv4.addresses {{ adresse_ipv4_numero_zero }}/24 ipv4.gateway {{ adresse_de_passerelle_une }} ipv4.dns  "{{ adresse_dns_une }},{{ adresse_dns_deux }}" ipv4.method manual
      tags: machine0
      
    - name: Create new user and generate SSH key
      ansible.builtin.user:
        name: "{{ hostname_machine_une }}"
        shell: /bin/bash
        groups: "{{ hostname_machine_une }},wheel"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        tags: machine0

      - name: Set password for new user
        ansible.builtin.command: echo "{{ hostname_machine_une }}"|passwd --stdin {{ hostname_machine_une }}
        tags: machine0

      - name: Move SSH config file to new user's home directory
        ansible.builtin.command: mv sshconfig /home/{{ hostname_machine_une }}/.ssh/config
        tags: machine0
        
      - name: CREATION DES DOSSIERS POUR LA CONFIG SSH
        ansible.builtin.file:
          path: home/{{ username.stdout }}/
          state: directory
        tags: machine0
      
      - name: Déplace le fichier de configuation des connexions SSH au bon endroit
        ansible.builtin.command: mv /home/{{ username.stdout }}/.bash/themes/agnoster-bash/.config83 /home/{{ username.stdout }}/.ssh/config

      - name: INSTALL nmap
        dnf:
          name: nmap
        tags: machine0
      
      - name: Execute scan_ip.sh script
        ansible.builtin.command: chmod o+x scan_ip.sh
        become: true
      
      - name: Execute scan_ip.sh script
        ansible.builtin.command: ./scan_ip.sh
        tags: machine0
      
      - name: CREATION DES DOSSIER .synchro POUR ROOT
        ansible.builtin.file:
          path: /root/.synchro
          state: directory
        tags: machine0
        
      - name: rend executable le fichier script authentification.sh
        ansible.builtin.command: chmod o+x authentification.sh
        become: true
        tags: machine0
      
      - name: Déplace le fichier de script authentifications.sh au bon endroit
        ansible.builtin.command: mv /home/{{ username.stdout }}/.deploiement/authentification.sh /root/.synchro/authentification.sh
      
      - name: Redn executable le fichier script sync.sh
        ansible.builtin.command: chmod o+x sync.sh
        become: true
        tags: machine0
      
      - name: Déplace le fichier de script sync.sh au bon endroit
        ansible.builtin.command: mv /home/{{ username.stdout }}/.deploiement/sync.sh /root/.synchro/sync.sh
        tags: machine0

     - name: Récupére l'utilisateur courant
       ansible.builtincommand: whoami
       register: username
       become_user: "{{ ansible_facts.hostname }}"
       tags: machine0

     - name: vérifie que la valeur est bien enregistré
       ansible.builtin.debug:
         var: username.stdout
       tags: machine0

     - name: Copier les polices de caractère sur la machine
       ansible.builtin.git:
         repo: https://github.com/adelfortin/fontspowerline
         dest: /home/{{ username.stdout }}/.fonts/ 
         clone: yes
         update: yes
       tags: machine0

     - name: Installe les polices de caractères sur la machine
       ansible.builtin.command: bash /home/{{ username.stdout }}/.fonts/install.sh

  
     - name: Installe les prompt personnalisé 
       ansible.builtin.git:
         repo: https://github.com/adelfortin/exportation
         dest: /home/{{ username.stdout }}/.bash/themes/agnoster-bash/
         clone: yes
         update: yes
       tags: machine0

     - name: CREATION DES DOSSIERS POUR ROOT
       ansible.builtin.file:
         path: /root/.bash/themes/agnoster-bash
         state: directory
       tags: machine0

     - name: Déplace le fichier de configuation BASHRC au bon endroit
       ansible.builtin.command: mv /home/{{ username.stdout }}/.bash/themes/agnoster-bash/.bashrc /home/{{ username.stdout }}/.bashrc
       tags: machine0

     - name: Installation du theme du prompt de root
       ansible.builtin.command: cp -f /home/{{ username.stdout }}/.bash/themes/agnoster-bash/agnoster.bash /root/.bash/themes/agnoster-bash/
       tags: machine0
    
     - name: Préparation du .bashrc de root
       ansible.builtin.command: cp /home/{{ username.stdout }}/.bashrc /root/
       tags: machine0
