---
- name: PROGRAMME DE SUPPRESSION DES CONFIG
  hosts: webservers
  become: true
  tasks:
    - name: Récupére l'utilisateur courant pour web1
      ansible.builtin.command: whoami
      register: username
      become_user: "{{ ansible_facts.hostname }}"

  - name: PROMPT DELETE | "{{ item.title }}"
    command: "rm -Rf {{ item.path }}"
    with_items:
      - { title : "Efface les configs de bash", path : "/home/{{ username.stdout }}/.bash" }
      - { title : "Efface les configs de fonts", path : "/home/{{ username.stdout }}/.fonts" }
      - { title : "Efface les configs de bash root", path : "/root/.bash" }
      - { title : "Efface le ficher .bashrc", path : "/home/{{ username.stdout }}/.bashrc" }
      - { title : "Efface le fichier .bashrc de root", path : "/root/.bashrc" }
    tags: prompt_delete

