---
- name: Configure network and user settings
hosts: all
become: true
vars:
ancienne_adresse: "192.168.1.1"
adresse_ipv4_numero_zero: "192.168.83.3"
interface_zero: "enp0s8"
adresse_ipv4_numero_une: "192.168.82.3"
interface_une: "enp0s9"
adresse_de_passerelle_une: 192.168.83.2
adresse_de_passerelle_deux: 192.168.82.1
adresse_dns_une: 10.156.32.33
adresse_dns_deux: 10.154.59.104
hostname_machine_une: "webserver1"
tasks:
- name: Copy SSH key to remote server
ansible.builtin.command: ssh-copy-id root@{{ ancienne_adresse }}

- name: Configure first interface
ansible.builtin.command: nmcli connection add type ethernet con-name INTERNET ifname {{ interface_zero }} ipv4.addresses {{ adresse_ipv4_numero_zero }}/24 ipv4.gateway {{ adresse_de_passerelle_une }} ipv4.dns  "{{ adresse_dns_une }},{{ adresse_dns_deux }}" ipv4.method manual

- name: Configure second interface
ansible.builtin.command: nmcli connection add type ethernet con-name INTERNET ifname {{ interface_une }} ipv4.addresses {{ adresse_ipv4_numero_une }}/24 ipv4.gateway {{ adresse_de_passerelle_deux }} ipv4.dns  "{{ adresse_dns_une }},{{ adresse_dns_deux }}" ipv4.method manual

- name: Create new user and generate SSH key
ansible.builtin.user:
  name: "{{ hostname_machine_une }}"
  shell: /bin/bash
  groups: "{{ hostname_machine_une }},wheel"
  generate_ssh_key: yes
  ssh_key_bits: 2048
  ssh_key_file: .ssh/id_rsa

- name: Set password for new user
ansible.builtin.command: echo "{{ hostname_machine_une }}"|passwd --stdin {{ hostname_machine_une }}

- name: Move SSH config file to new user's home directory
ansible.builtin.command: mv sshconfig /home/{{ hostname_machine_une }}/.ssh/config
