---
  - name: Execute transformer_en_routeur.sh script
    ansible.builtin.command: mv /root//deploy/configsshmachine8 /root/.deploy/config
    become: true
    
  - name: DONNE LES DROITS D'EXECUTION POUR LE SCRIPT DE REDEMARRAGE
    ansible.builtin.command: chmod a+x /root/.deploy/configmachine8.sh
    become: true

  - name: Execute transformer_en_routeur.sh script
    ansible.builtin.command: bash /root//deploy/configmachine8.sh
    
  - name: DONNE LES DROITS D'EXECUTION POUR LE SCRIPT DE REDEMARRAGE
    ansible.builtin.command: chmod a+x /root/.deploy/cloturemachine8.sh
    become: true

  - name: Execute transformer_en_routeur.sh script
    ansible.builtin.command: bash /root//deploy/cloturemachine8.sh
      
  - name: DONNE LES DROITS D'EXECUTION POUR LE SCRIPT DE REDEMARRAGE
    ansible.builtin.command: chmod a+x /root/.deploy/relai.sh
    become: true

  - name: Execute transformer_en_routeur.sh script
    ansible.builtin.command: bash /root//deploy/relai.sh
    become: true
