---   
  - name: Set machine facts
    set_fact:
      machine: "{{ item.0 }}"
    with_indexed_items: "{{ groups['machine_sans_configuration'] }}"
      
  - name: Debug
    debug: 
      msg: "{{ machine }}"

  - name: CREATION DES DOSSIERS POUR LE DEPLOIEMENT
    ansible.builtin.file:
      path: /root/.deploy
      state: directory

  - name: COPIE DES FICHIERS DE CONFIGURATIONS DE LA MACHINE
    ansible.builtin.copy:
      src: /root/.deploy/config{{ machine }}.sh
      dest: /root/.deploy/config{{ machine }}.sh
      remote_src: yes

  - name: DONNE LES DROITS D'EXECUTION POUR LE SCRIPT DE CONFIGURATION DE LA MACHINE
    ansible.builtin.command: chmod o+x /root/.deploy/config{{ machine }}.sh

  - name: Execute transformer_en_routeur.sh script
    ansible.builtin.command: bash /root/.deploy/config{{ machine }}.sh

  - name: COPIE DES FICHIERS DE CONFIGURATIONS SSH DE LA MACHINE
    ansible.builtin.copy:
      src: /root/.deploy/configssh{{ machine }}
      dest: /home/{{ ansible_facts.hostname }}/.ssh/config
      remote_src: yes

  - name: COPIE DES FICHIERS DE CONFIGURATIONS DE BASH DE LA MACHINE POUR L'UTILISATEUR
    ansible.builtin.copy:
      src: /root/.deploy/.bashrc
      dest: /home/{{ ansible_facts.hostname }}/.bashrc
      remote_src: yes

  - name: COPIE DES FICHIERS DE CONFIGURATIONS DE BASH DE LA MACHINE POUR ROOT
    ansible.builtin.copy:
      src: /root/.deploy/.bashrc
      dest: /root/.bashrc
      remote_src: yes

  - name: COPIE DES FICHIERS DE CONFIGURATIONS DU THEME DU PROMPT DE BASH DE LA MACHINE POUR L'UTILISATEUR
    ansible.builtin.copy:
      src: /root/.deploy/agnoster.bash
      dest: /home/{{ ansible_facts.hostname }}/.bash/themes/agnoster-bash/agnoster.bash
      remote_src: yes

  - name: CREATION DES DOSSIERS POUR LE THEME DU PROMPT DE BASH DE LA MACHINE POUR ROOT
    ansible.builtin.file:
      path: /root/.bash/themes/agnoster-bash
      state: directory

  - name: COPIE DES FICHIERS DE CONFIGURATIONS DU THEME DU PROMPT DE BASH DE LA MACHINE POUR ROOT
    ansible.builtin.copy:
      src: /root/.deploy/agnoster.bash
      dest: /root/.bash/themes/agnoster-bash/agnoster.bash
      remote_src: yes

  # Configuration et installation de DNF et EPEL
  - name: CONFIG DNF | Ajout du proxy dans le fichier de configuration de dnf
    lineinfile:
      path: /etc/dnf/dnf.conf
      line: proxy=http://proxy.infra.dgfip:3128

  - name: INSTALL git
    dnf:
      name: git

  - name: CONFIG LE PROXY POUR GITHUB
    ansible.builtin.command: git config --global http.proxy http://proxy.infra.dgfip:3128

  - name: Récupére l'utilisateur courant
    ansible.builtin.command: whoami
    register: username
    become_user: "{{ ansible_facts.hostname }}"

  - name: vérifie que la valeur est bien enregistré
    ansible.builtin.debug:
      var: username.stdout

  - name: Copier les polices de caractère sur la machine
    ansible.builtin.git:
      repo: https://github.com/adelfortin/fontspowerline
      dest: /home/{{ username.stdout }}/.fonts/
      clone: yes
      update: yes

  - name: Installe les polices de caractères sur la machine
    ansible.builtin.command: bash /home/{{ username.stdout }}/.fonts/install.sh
