---   
  - name: Set machine facts
    set_fact:
      machine: "machine{{ host_index }}"
    when: inventory_hostname == item
    loop: "{{ groups['machine_sans_configuration'] }}"
    loop_control:
      index_var: host_index
      
  - name: Debug
    debug: 
      msg: machine

  - name: CREATION DES DOSSIERS POUR LE DEPLOIEMENT
    ansible.builtin.file:
      path: /root/.deploy
      state: directory
      
  - name: COPIE DES FICHIERS DE CONFIGURATIONS DE BASHRC
    ansible.builtin.copy:
      src: /root/.deploy/.bashrc
      dest: /root/.deploy/.bashrc
 
  - name: COPIE DES FICHIERS DE CONFIGURATIONS DU THEME AGNOSTER BASH
    ansible.builtin.copy:
      src: /root/.deploy/agnoster.bash
      dest: /root/.deploy/agnoster.bash
      
  - name: COPIE DES FICHIERS DE CONFIGURATIONS DE LA MACHINE
    ansible.builtin.copy:
      src: /root/.deploy/transformer_en_routeur.sh
      dest: /root/.deploy/transformer_en_routeur.sh
 
  - name: DONNE LES DROITS D'EXECUTION POUR LE SCRIPT DE CONFIGURATION DE LA MACHINE
    ansible.builtin.command: chmod o+x /root/.deploy/transformer_en_routeur.sh
    become: true

  - name: COPIE DES FICHIERS DE CONFIGURATIONS DE LA MACHINE
    ansible.builtin.copy:
      src: /root/.deploy/config{{ machine }}.sh
      dest: /root/.deploy/config{{ machine }}.sh
      
  - name: COPIE DES FICHIERS DE CONFIGURATIONS SSH DE LA MACHINE
    ansible.builtin.copy:
      src: /root/.deploy/configssh{{ machine }}
      dest: /root/.deploy/config
    become: true

  - name: DONNE LES DROITS D'EXECUTION POUR LE SCRIPT DE CONFIGURATION DE LA MACHINE
    ansible.builtin.command: chmod o+x /root/.deploy/config{{ machine }}.sh
    become: true

  - name: EXECUTE LE SCRIPT DE CONFIGURATION DE LA MACHINE
    ansible.builtin.command: bash /root/.deploy/config{{ machine }}.sh
    become: true

  # Configuration et installation de DNF et EPEL
  - name: CONFIG DNF | Ajout du proxy dans le fichier de configuration de dnf
    lineinfile:
      path: /etc/dnf/dnf.conf
      line: proxy=http://proxy.infra.dgfip:3128
    become: true
    
  - name: COPIE DES FICHIERS DE CONFIGURATIONS DE LA MACHINE
    ansible.builtin.copy:
      src: /root/.deploy/untarscript.sh
      dest: /root/.deploy/untarscript.sh
      
  - name: COPIE DES FICHIERS DE CONFIGURATIONS DE LA MACHINE
    ansible.builtin.copy:
      src: /root/powerline_fonts.tar.gz
      dest: /root/powerline_fonts.tar.gz
    
  - name: DONNE LES DROITS D'EXECUTION POUR LE SCRIPT D'INSTALLATION DES POLICES DE CARACTERES
    ansible.builtin.command: chmod o+x /root/.deploy/untarscript.sh
    become: true

  - name: EXECUTE LE SCRIPT D'INSTALLATION DES POLICES DE CARACTERES
    ansible.builtin.command: bash /root/.deploy/untarscript.sh
    become: true
