---
- name: Configure network and user settings
  hosts: all
  become: true
  tasks:
    - name: Determine index of current host
      set_fact:
        host_index: "{{ groups['machine_sans_configuration'].index(ansible_hostname) }}"
