---   
  - name: Set machine facts
    set_fact:
      machine: "machine{{ host_index }}"
    when: inventory_hostname == item
    loop: "{{ groups['machine_sans_configuration'] }}"
    loop_control:
      index_var: host_index
      
  - name: COPIE DES FICHIERS DE CONFIGURATIONS AVANT REDEMARRAGE
    ansible.builtin.copy:
      src: /root/.deploy/cloture{{ machine }}.sh
      dest: /root/.deploy/cloture{{ machine }}.sh
      
  - name: DONNE LES DROITS D'EXECUTION POUR LE SCRIPT DE REDEMARRAGE
    ansible.builtin.command: chmod o+x /root/.deploy/cloture{{ machine }}.sh
    become: true

  - name: EXECUTE LE SCRIPT DE REDEMARRAGE
    ansible.builtin.command: bash /root/.deploy/cloture{{ machine }}.sh
    become: true
  
  - name: Attendre la reconnexion
    ansible.builtin.wait_for_connection:
      tiemout: 900
